/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface AuditError {
  createdAt: Generated<Date>;
  deletedAt: Date | null;
  endpoint: string;
  errorTrace: string | null;
  id: string;
  updatedAt: Generated<Date>;
}

export interface User {
  createdAt: Generated<Date>;
  createdBy: string | null;
  deletedAt: Date | null;
  deletedBy: string | null;
  email: string;
  id: string;
  name: string;
  password: string;
  updatedAt: Generated<Date>;
  updatedBy: string | null;
  username: string;
}

export interface DB {
  auditError: AuditError;
  user: User;
}
