/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Employee {
  address: string;
  createdAt: Generated<Date>;
  deletedAt: Date | null;
  departmentName: string;
  domicile: string;
  email: string;
  emergencyNumber: string;
  employeeStatus: "KONTRAK" | "MAGANG" | "TETAP";
  gender: "LAKI-LAKI" | "PEREMPUAN";
  id: string;
  joinDate: Generated<Date>;
  kkNumber: string;
  ktpNumber: string;
  leaveQuota: number;
  name: string;
  payroll: number;
  phone: string;
  taxStatus: "K1" | "K2" | "S0";
  updatedAt: Generated<Date>;
}

export interface User {
  createdAt: Generated<Date>;
  deletedAt: Date | null;
  email: string;
  id: string;
  password: string;
  updatedAt: Generated<Date>;
  username: string;
}